### API REST - FABSOFT

######################## USUARIO

### GET ALL - OK
GET http://localhost:8080/api/v1/usuario

### GET BY ID - OK
GET http://localhost:8080/api/v1/usuario/1

### POST NEW USER - OK
POST http://localhost:8080/api/v1/usuario
Content-Type: application/json

{
    "nome": "furão",
    "email": "ze@ze.com.br",
    "senha": "abcd1234"
}

### PUT USER - OK
PUT http://localhost:8080/api/v1/usuario/1
Content-Type: application/json

{
"nome": "Clebinho da 12",
"email": "joaosilva@email.com",
"senha": "novaSenha456"
}

### DELETE - OK
DELETE http://localhost:8080/api/v1/usuario/1

######################## PAPEL

### GET ALL PAPEL - OK
GET http://localhost:8080/api/v1/papeis

### GET BY ID - OK
GET http://localhost:8080/api/v1/papeis/1

### POST NEW PAPEL - OK
POST http://localhost:8080/api/v1/papeis
Content-Type: application/json

{
"nome": "Administrador"
}

### PUT PAPEL - OK
PUT http://localhost:8080/api/v1/papeis/1
Content-Type: application/json

{
"nome": "Usuário Comum"
}

### DELETE - OK
DELETE http://localhost:8080/api/v1/papeis/1

######################## ENDEREÇO

### GET ALL ENDEREÇO - OK
GET http://localhost:8080/api/v1/enderecos

### GET BY ID
GET http://localhost:8080/api/v1/enderecos/1

### POST NEW ENDEREÇO
POST http://localhost:8080/api/v1/enderecos
Content-Type: application/json

{
"rua": "Av. Central",
"numero": "100",
"cidade": "Curitiba",
"estado": "PR",
"cep": "80000000"
}

### PUT ENDEREÇO
PUT http://localhost:8080/api/v1/enderecos/1
Content-Type: application/json

{
"rua": "Rua Nova",
"numero": "101",
"cidade": "Londrina",
"estado": "PR",
"cep": "86000000"
}

### DELETE
DELETE http://localhost:8080/api/v1/enderecos/1

######################## CATEGORIA EVENTO

### GET ALL CATEGORIA EVENTO - OK
GET http://localhost:8080/api/v1/categorias-evento

### GET BY ID - OK
GET http://localhost:8080/api/v1/categorias-evento/1

### POST NEW CATEGORIA EVENTO - OK
POST http://localhost:8080/api/v1/categorias-evento
Content-Type: application/json

{
"nome": "Palestra"
}

### PUT CATEGORIA EVENTO - OK
PUT http://localhost:8080/api/v1/categorias-evento/1
Content-Type: application/json

{
"nome": "Workshop"
}

### DELETE - OK
DELETE http://localhost:8080/api/v1/categorias-evento/1

######################## EVENTO

### GET ALL EVENTO - OK
GET http://localhost:8080/api/v1/eventos

### GET BY ID - OK
GET http://localhost:8080/api/v1/eventos/4

### POST NEW EVENTO - OK
POST http://localhost:8080/api/v1/eventos
Content-Type: application/json

{
"nome": "Semana Acadêmica",
"local": "Auditório Central",
"data": "2025-06-10",
"hora": "19:00",
"usuario": {
"id": 1
},
"categoria": {
"id": 2
}
}

### PUT EVENTO - OK
PUT http://localhost:8080/api/v1/eventos/4
Content-Type: application/json

{
"nome": "Feira de Tecnologia",
"local": "Bloco C",
"data": "2025-06-15",
"hora": "14:00",
"usuario": {
"id": 1
},
"categoria": {
"id": 3
}
}

### DELETE - OK
DELETE http://localhost:8080/api/v1/eventos/4

######################## PARTICIPAÇÃO

### GET ALL PARTICIPAÇÃO - OK
GET http://localhost:8080/api/v1/participacoes

### GET BY ID - OK
GET http://localhost:8080/api/v1/participacoes/1

### POST NEW PARTICIPAÇÃO - OK
POST http://localhost:8080/api/v1/participacoes
Content-Type: application/json

{
"usuario": {
"id": 3
},
"evento": {
"id": 1
},
"confirmado": true
}

### PUT PARTICIPAÇÃO - OK
PUT http://localhost:8080/api/v1/participacoes/3
Content-Type: application/json

{
"usuario": {
"id": 3
},
"evento": {
"id": 1
},
"confirmado": false
}

### DELETE - OK
DELETE http://localhost:8080/api/v1/participacoes/4